// Mock user data
export const mockUser = {
   id: 1,
   username: "JohnDoe",
   email: "john@example.com",
   virtualCoins: 5000,
   realMoney: 100.5,
   joinedDate: "2023-01-15",
   referralCode: "JOHN123",
   referralBonus: 250,
   avatar: "https://randomuser.me/api/portraits/men/85.jpg",
   level: 28,
   xp: 2800,
   xpToNextLevel: 3000,
   winRate: 62,
   totalBattles: 124,
   wonBattles: 77,
   lostBattles: 47,
   badges: ["rising-star", "crypto-novice", "cricket-enthusiast"],
   favoriteCategories: ["Crypto", "Cricket"],
   streak: 5,
   rank: 5,
   achievements: [
      { id: 1, name: "First Win", description: "Win your first prediction battle", completed: true, date: "2023-01-20" },
      { id: 2, name: "High Roller", description: "Place a bet of 1000 coins or more", completed: true, date: "2023-02-15" },
      { id: 3, name: "Winning Streak", description: "Win 5 battles in a row", completed: true, date: "2023-03-10" },
      {
         id: 4,
         name: "Prediction Master",
         description: "Achieve a 60% win rate with at least 100 battles",
         completed: true,
         date: "2023-04-05",
      },
      { id: 5, name: "Category Expert", description: "Win 20 battles in a single category", completed: false, progress: 15 },
   ],
   notifications: [
      {
         id: 1,
         type: "win",
         message: "You won 500 coins in 'Bitcoin will cross $65,000 this week'",
         read: false,
         date: new Date(Date.now() - 3600000).toISOString(),
      },
      {
         id: 2,
         type: "battle_joined",
         message: "SoccerPro joined your 'Messi to score' battle",
         read: true,
         date: new Date(Date.now() - 86400000).toISOString(),
      },
      {
         id: 3,
         type: "level_up",
         message: "Congratulations! You reached Level 28",
         read: true,
         date: new Date(Date.now() - 172800000).toISOString(),
      },
   ],
};

// Mock transactions
export const mockTransactions = [
   {
      id: 1,
      type: "WIN",
      amount: 500,
      date: new Date(Date.now() - 86400000).toISOString(),
      description: "Cricket match win",
      category: "Cricket",
      battle: "India vs Australia - Who will win?",
      categoryColor: "bg-secondary-500",
      icon: "🏆",
   },
   {
      id: 2,
      type: "LOSS",
      amount: -200,
      date: new Date(Date.now() - 172800000).toISOString(),
      description: "Crypto prediction loss",
      category: "Crypto",
      battle: "Bitcoin will cross $65,000 this week",
      categoryColor: "bg-primary-500",
      icon: "📉",
   },
   {
      id: 3,
      type: "DEPOSIT",
      amount: 1000,
      date: new Date(Date.now() - 259200000).toISOString(),
      description: "Added funds",
      method: "Credit Card",
      transactionId: "TXN123456789",
      icon: "💳",
   },
   {
      id: 4,
      type: "WIN",
      amount: 350,
      date: new Date(Date.now() - 345600000).toISOString(),
      description: "E-Sports prediction win",
      category: "E-Sports",
      battle: "Fnatic to win Valorant Champions 2024",
      categoryColor: "bg-neon-purple",
      icon: "🏆",
   },
   {
      id: 5,
      type: "REFERRAL",
      amount: 100,
      date: new Date(Date.now() - 432000000).toISOString(),
      description: "Referral bonus",
      referredUser: "AlexSmith",
      icon: "👥",
   },
   {
      id: 6,
      type: "BONUS",
      amount: 200,
      date: new Date(Date.now() - 518400000).toISOString(),
      description: "Level up bonus",
      level: 28,
      icon: "🎁",
   },
   {
      id: 7,
      type: "WITHDRAWAL",
      amount: -500,
      date: new Date(Date.now() - 604800000).toISOString(),
      description: "Withdrawal to bank account",
      method: "Bank Transfer",
      status: "Completed",
      transactionId: "WTH987654321",
      icon: "🏦",
   },
];

// Mock battles
export const mockBattles = [
   {
      id: 1,
      category: "Cricket",
      title: "India vs Australia - Who will win?",
      description: "Predict the winner of the T20 World Cup match between India and Australia.",
      entryFee: 200,
      status: "open",
      creator: {
         id: 2,
         username: "CricketFan",
         prediction: "YES",
         avatar: "https://randomuser.me/api/portraits/men/32.jpg",
      },
      opponent: null,
      endTime: new Date(Date.now() + 86400000).toISOString(), // 24 hours from now
      categoryColor: "bg-secondary-500",
      categoryGradient: "from-secondary-500 to-neon-green",
   },
   {
      id: 2,
      category: "Crypto",
      title: "Bitcoin will cross $65,000 this week",
      description: "Will Bitcoin break through the $65,000 resistance level by the end of this week?",
      entryFee: 500,
      status: "in-progress",
      creator: {
         id: 3,
         username: "CryptoKing",
         prediction: "YES",
         avatar: "https://randomuser.me/api/portraits/men/42.jpg",
      },
      opponent: {
         id: 1,
         username: "JohnDoe",
         prediction: "NO",
         avatar: "https://randomuser.me/api/portraits/men/85.jpg",
      },
      endTime: new Date(Date.now() + 43200000).toISOString(), // 12 hours from now
      categoryColor: "bg-primary-500",
      categoryGradient: "from-primary-500 to-neon-blue",
   },
   {
      id: 3,
      category: "E-Sports",
      title: "Fnatic to win Valorant Champions 2024",
      description: "Will Fnatic win the Valorant Champions 2024 tournament?",
      entryFee: 300,
      status: "completed",
      creator: {
         id: 1,
         username: "JohnDoe",
         prediction: "YES",
         avatar: "https://randomuser.me/api/portraits/men/85.jpg",
      },
      opponent: {
         id: 4,
         username: "GamerPro",
         prediction: "NO",
         avatar: "/images/avatars/avatar-4.webp",
      },
      result: "YES",
      winner: {
         id: 1,
         username: "JohnDoe",
         avatar: "https://randomuser.me/api/portraits/men/85.jpg",
      },
      endTime: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
      categoryColor: "bg-neon-purple",
      categoryGradient: "from-neon-purple to-neon-pink",
   },
   {
      id: 4,
      category: "Football",
      title: "Man City vs Arsenal - Over 2.5 goals?",
      description: "Will the Premier League match between Manchester City and Arsenal have more than 2.5 goals?",
      entryFee: 250,
      status: "open",
      creator: {
         id: 5,
         username: "SportsFan",
         prediction: "YES",
         avatar: "/images/avatars/avatar-5.webp",
      },
      opponent: null,
      endTime: new Date(Date.now() + 172800000).toISOString(), // 48 hours from now
      categoryColor: "bg-accent-500",
      categoryGradient: "from-accent-500 to-neon-yellow",
   },
   {
      id: 5,
      category: "Crypto",
      title: "Ethereum will outperform Bitcoin this month",
      description: "Will Ethereum's price performance exceed Bitcoin's by the end of this month?",
      entryFee: 1000,
      status: "open",
      creator: {
         id: 6,
         username: "CryptoWhale",
         prediction: "YES",
         avatar: "/images/avatars/avatar-6.webp",
      },
      opponent: null,
      endTime: new Date(Date.now() + 604800000).toISOString(), // 7 days from now
      categoryColor: "bg-primary-500",
      categoryGradient: "from-primary-500 to-neon-blue",
   },
   {
      id: 6,
      category: "E-Sports",
      title: "CS:GO - NaVi to win against FaZe",
      description: "Will Natus Vincere defeat FaZe Clan in their upcoming CS:GO match?",
      entryFee: 400,
      status: "open",
      creator: {
         id: 7,
         username: "ESportsBet",
         prediction: "YES",
         avatar: "/images/avatars/avatar-7.webp",
      },
      opponent: null,
      endTime: new Date(Date.now() + 259200000).toISOString(), // 3 days from now
      categoryColor: "bg-neon-purple",
      categoryGradient: "from-neon-purple to-neon-pink",
   },
   {
      id: 7,
      category: "Football",
      title: "Messi to score in next Inter Miami match",
      description: "Will Lionel Messi score at least one goal in the next Inter Miami match?",
      entryFee: 350,
      status: "in-progress",
      creator: {
         id: 8,
         username: "MessiFan",
         prediction: "YES",
         avatar: "/images/avatars/avatar-8.webp",
      },
      opponent: {
         id: 9,
         username: "SoccerPro",
         prediction: "NO",
         avatar: "/images/avatars/avatar-9.webp",
      },
      endTime: new Date(Date.now() + 129600000).toISOString(), // 1.5 days from now
      categoryColor: "bg-accent-500",
      categoryGradient: "from-accent-500 to-neon-yellow",
   },
   {
      id: 8,
      category: "Cricket",
      title: "Virat Kohli to score a century",
      description: "Will Virat Kohli score a century in the upcoming ODI match?",
      entryFee: 450,
      status: "open",
      creator: {
         id: 10,
         username: "CricketExpert",
         prediction: "YES",
         avatar: "/images/avatars/avatar-10.webp",
      },
      opponent: null,
      endTime: new Date(Date.now() + 345600000).toISOString(), // 4 days from now
      categoryColor: "bg-secondary-500",
      categoryGradient: "from-secondary-500 to-neon-green",
   },
];

// Mock leaderboard
export const mockLeaderboard = [
   {
      id: 6,
      username: "CryptoWhale",
      totalWinnings: 25000,
      rank: 1,
      avatar: "/images/avatars/avatar-6.webp",
      winRate: 78,
      badges: ["crypto-expert", "diamond-predictor"],
      level: 42,
   },
   {
      id: 3,
      username: "CryptoKing",
      totalWinnings: 18500,
      rank: 2,
      avatar: "/images/avatars/avatar-3.webp",
      winRate: 72,
      badges: ["crypto-expert", "gold-predictor"],
      level: 38,
   },
   {
      id: 7,
      username: "PredictionMaster",
      totalWinnings: 15200,
      rank: 3,
      avatar: "/images/avatars/avatar-7.webp",
      winRate: 68,
      badges: ["all-rounder", "silver-predictor"],
      level: 35,
   },
   {
      id: 4,
      username: "GamerPro",
      totalWinnings: 12800,
      rank: 4,
      avatar: "/images/avatars/avatar-4.webp",
      winRate: 65,
      badges: ["esports-expert", "bronze-predictor"],
      level: 31,
   },
   {
      id: 1,
      username: "JohnDoe",
      totalWinnings: 10500,
      rank: 5,
      avatar: "https://randomuser.me/api/portraits/men/85.jpg",
      winRate: 62,
      badges: ["rising-star"],
      level: 28,
   },
   {
      id: 8,
      username: "MessiFan",
      totalWinnings: 9800,
      rank: 6,
      avatar: "/images/avatars/avatar-8.webp",
      winRate: 60,
      badges: ["football-expert"],
      level: 25,
   },
   {
      id: 2,
      username: "CricketFan",
      totalWinnings: 8200,
      rank: 7,
      avatar: "/images/avatars/avatar-2.webp",
      winRate: 58,
      badges: ["cricket-expert"],
      level: 23,
   },
   {
      id: 9,
      username: "SoccerPro",
      totalWinnings: 7500,
      rank: 8,
      avatar: "/images/avatars/avatar-9.webp",
      winRate: 55,
      badges: ["football-expert"],
      level: 21,
   },
   {
      id: 5,
      username: "SportsFan",
      totalWinnings: 6300,
      rank: 9,
      avatar: "/images/avatars/avatar-5.webp",
      winRate: 52,
      badges: ["sports-enthusiast"],
      level: 19,
   },
   {
      id: 10,
      username: "CricketExpert",
      totalWinnings: 5100,
      rank: 10,
      avatar: "/images/avatars/avatar-10.webp",
      winRate: 50,
      badges: ["cricket-expert"],
      level: 17,
   },
];

// Mock categories
export const categories = [
   { id: 1, name: "Crypto", icon: "💰", color: "bg-primary-500", gradient: "from-primary-500 to-neon-blue", image: "/images/crypto.webp" },
   {
      id: 2,
      name: "Cricket",
      icon: "🏏",
      color: "bg-secondary-500",
      gradient: "from-secondary-500 to-neon-green",
      image: "/images/cricket.webp",
   },
   {
      id: 3,
      name: "Football",
      icon: "⚽",
      color: "bg-accent-500",
      gradient: "from-accent-500 to-neon-yellow",
      image: "/images/football.webp",
   },
   {
      id: 4,
      name: "E-Sports",
      icon: "🎮",
      color: "bg-neon-purple",
      gradient: "from-neon-purple to-neon-pink",
      image: "/images/esports.webp",
   },
];
